FROM tmt-data as docker_web

FROM python:3.11.1-slim-bullseye as generate_data

# Software
COPY . /srv/web/
COPY docker/entry-point-web.sh /srv/entry-point.sh

# Locale ca-ES
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales

RUN sed -i -e 's/# ca_ES.UTF-8 UTF-8/ca_ES.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales

ENV LC_ALL=ca_ES.utf-8

# Data
COPY --from=docker_web /static/index_data.json /srv/web/
COPY --from=docker_web /static/glossary.json /srv/web/
COPY --from=docker_web /static/projects.json /srv/web/

WORKDIR /srv/web
RUN pip install -r /srv/web/requirements_indexer.txt
RUN python index_creation.py
RUN rm index_data.json

RUN python term_creator.py
RUN rm glossary.json

FROM python:3.11.1-slim-bullseye

RUN apt-get update && apt-get install python3-dev gettext -y

COPY --from=generate_data /srv/ /srv/

RUN pip install -r /srv/web/requirements.txt

EXPOSE 8080

WORKDIR /srv
ENTRYPOINT bash /srv/entry-point.sh

