FROM python:3.10.2-slim-bullseye

RUN apt-get update && apt-get install libhunspell-dev zip -y
RUN apt-get install openjdk-11-jdk wget -y

EXPOSE 7001

ENV LT_VERSION 5.7
ENV ROOT /srv
ENV LT $ROOT/LanguageTool-$LT_VERSION

RUN mkdir -p $ROOT
WORKDIR $ROOT

COPY entry-point-lt.sh /srv/entrypoint.sh

# LanguageTool
RUN wget -q https://languagetool.org/download/LanguageTool-$LT_VERSION.zip && unzip LanguageTool-$LT_VERSION.zip && rm -f LanguageTool-$LT_VERSION.zip

ENTRYPOINT /srv/entrypoint.sh $LT
