FROM python:3.9.10-slim-bullseye

ENV DIR /srv/dev
ENV DIR_TMT_GIT /srv/dev/tm-git

RUN apt-get update && apt-get install python3-dev libhunspell-dev libyaml-dev gettext zip mercurial bzr ruby git curl wget g++ subversion bzip2 python2-dev -y
RUN curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash && mv ./tx /usr/bin/
RUN mkdir -p $DIR

#Pology
RUN apt-get install cmake -y
RUN wget -q http://pology.nedohodnik.net/release/pology-0.12.tar.bz2
RUN tar xvjf pology-0.12.tar.bz2
WORKDIR pology-0.12
RUN mkdir build && cd build && cmake .. && make && make install
RUN gem install i18n-translators-tools

# Locale ca-ES
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales

RUN sed -i -e 's/# ca_ES.UTF-8 UTF-8/ca_ES.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales

COPY requirements.txt/ $DIR_TMT_GIT/
RUN pip install -r $DIR_TMT_GIT/requirements.txt
 
WORKDIR $DIR
COPY src/ $DIR_TMT_GIT/src/
COPY deployment/ $DIR_TMT_GIT/deployment/
COPY source-pos/ $DIR_TMT_GIT/source-pos/
COPY cfg/ $DIR_TMT_GIT/cfg/
COPY docker/ $DIR_TMT_GIT/docker/
COPY integration-tests/ $DIR_TMT_GIT/integration-tests/

# What get's executed on Run
ENTRYPOINT bash $DIR_TMT_GIT/docker/entry-point-builder.sh $DIR $DIR_TMT_GIT
