FROM tmt-webapp
 
# Software
RUN apt-get install httping -y
COPY integration-tests /srv/integration-tests
COPY docker/entry-point-web-test.sh /srv/

WORKDIR /srv
ENTRYPOINT bash /srv/entry-point-web-test.sh

