FROM python:3.12.2-slim-bullseye

ENV DIR /srv/dev
ENV DIR_TMT_GIT /srv/dev/tm-git

RUN apt-get update && apt-get install python3-dev libhunspell-dev libyaml-dev gettext zip mercurial bzr ruby git curl wget g++ subversion bzip2 -y
RUN curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash && mv ./tx /usr/bin/
RUN mkdir -p $DIR

#Pology
RUN apt-get install cmake -y
RUN git clone --depth 1 https://invent.kde.org/sdk/pology.git
WORKDIR pology
# Pology does not do releases. We do not fix a version and rollout automatically the latest rules fixes
RUN mkdir build && cd build && cmake .. && make && make install
RUN gem install i18n-translators-tools

# Locale ca-ES
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales

RUN sed -i -e 's/# ca_ES.UTF-8 UTF-8/ca_ES.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales

COPY requirements.txt/ $DIR_TMT_GIT/
RUN pip install --no-cache-dir -r $DIR_TMT_GIT/requirements.txt

WORKDIR $DIR
COPY src/ $DIR_TMT_GIT/src/
COPY deployment/ $DIR_TMT_GIT/deployment/
COPY source-pos/ $DIR_TMT_GIT/source-pos/
COPY cfg/ $DIR_TMT_GIT/cfg/
COPY docker/ $DIR_TMT_GIT/docker/

# Get the credentials file for Transifex and COPY it to user directory (where the cli reads it)
COPY cfg/credentials/transifexrc* /root/.transifexrc

# What get's executed on Run
ENTRYPOINT bash $DIR_TMT_GIT/docker/entry-point-builder.sh $DIR $DIR_TMT_GIT
