FROM tmt-data as docker_web

FROM python:3.11.1-slim-bullseye as generate_data

# Software
COPY src/web /srv/web/
COPY src/terminology/ /srv/terminology/
COPY src/builder/ /srv/builder/
COPY docker/entry-point-web.sh /srv/entry-point.sh

# Data
COPY --from=docker_web /static/index_data.json /srv/web/
COPY --from=docker_web /static/projects.json /srv/web/
COPY --from=docker_web /static/index.json /srv/web/
COPY --from=docker_web /static/statistics.db3 /srv/web/
COPY --from=docker_web /static/glossary.db3 /srv/web/

WORKDIR /srv/web
RUN pip install -r /srv/web/requirements_indexer.txt
RUN python index_creation.py
RUN rm index_data.json

FROM python:3.11.1-slim-bullseye

RUN apt-get update && apt-get install python3-dev gettext -y

COPY --from=generate_data /srv/ /srv/

RUN pip install -r /srv/web/requirements.txt

EXPOSE 8080

WORKDIR /srv
ENTRYPOINT bash /srv/entry-point.sh

