pology:
    - rules-dir: quality/pology
    - python2: /usr/bin/python2
    - posieve: /usr/local/bin/posieve
    - header-fix: '{0} set-header -sfield:"Language:ca" -screate "{1}"'
    - command: '{0} --skip-obsolete --coloring-type=html check-rules {1} "{2}" > "{3}"'
    - rules:
        - /upstream/false-friends.rules
        - /upstream/keys.rules
        - /catalan-pology-rules/punctuation.rules
        - /catalan-pology-rules/date-format.rules
        - /catalan-pology-rules/terminology-sc.rules
        - /catalan-pology-rules/iso_639.rules
        - /catalan-pology-rules/acronyms.rules
        - /catalan-pology-rules/iso_4217.rules
        - /catalan-pology-rules/tags.rules
        - /catalan-pology-rules/abbreviations.rules
        - /catalan-pology-rules/gender-neutralization.rules

lt:
    - lt_output: output/quality
    - disabled-rules: WHITESPACE_RULE,UPPERCASE_SENTENCE_START,CAMI_DE,ESPAIS_QUE_FALTEN_PUNTUACIO,PUNT_FINAL,ESPAIS_QUE_FALTEN_PUNTUACIO,ESPAI_DARRERE_PUNTICOMA,VERBS_NOMSPROPIS,COMMA_PARENTHESIS_WHITESPACE
    - enabled-rules: EXIGEIX_PLURALS
    - server: http://localhost:7001/v2/check
    - command: 'curl --data "language=ca-ES" --data "enabledRules={0}" --data "disabledRules={1}" --data-urlencode "text@{2}" {3} > "{4}" 2>/dev/null'
    - lt-html-dir: quality/lt
